CC=g++
CFLAGS=-std=c++14 -Wall -Werror -O2

iteratorTestNode: iteratorTestNode Graph.h
	  $(CC) $(CFLAGS) iteratorTestNode.cpp -o iteratorTestNode

mergeReplace: mergeReplace Graph.h
	  $(CC) $(CFLAGS) mergeReplace.cpp -o mergeReplace

iteratorTestEdge: iteratorTestEdge.cpp Graph.h
	  $(CC) $(CFLAGS) iteratorTestEdge.cpp -o iteratorTestEdge

deletion: deletion.cpp Graph.h
	  $(CC) $(CFLAGS) deletion.cpp -o deletion

iteratorTest: iteratorTest.cpp Graph.h
	  $(CC) $(CFLAGS) iteratorTest.cpp -o iteratorTest

postIncrement: postIncrement.cpp Graph.h
	  $(CC) $(CFLAGS) postIncrement.cpp -o postIncrement

sameEdges: sameEdges.cpp Graph.h
	  $(CC) $(CFLAGS) sameEdges.cpp -o sameEdges

addDeleteEdge: addDeleteEdge.cpp Graph.h
	  $(CC) $(CFLAGS) addDeleteEdge.cpp -o addDeleteEdge

iteratorMemory: iteratorMemory.cpp Graph.h
	  $(CC) $(CFLAGS) iteratorMemory.cpp -o iteratorMemory	

addDelete: addDelete.cpp Graph.h
	  $(CC) $(CFLAGS) addDelete.cpp -o addDelete

test1: test1.cpp Graph.h
	  $(CC) $(CFLAGS) test1.cpp -o test1
	
test2: test2.cpp Graph.h
	  $(CC) $(CFLAGS) test2.cpp -o test2
	
test3: test3.cpp Graph.h
	  $(CC) $(CFLAGS) test3.cpp -o test3
	
test4: test4.cpp Graph.h
	  $(CC) $(CFLAGS) test4.cpp -o test4
	
test5: test5.cpp Graph.h
	  $(CC) $(CFLAGS) test5.cpp -o test5
	
test6: test6.cpp Graph.h
	  $(CC) $(CFLAGS) test6.cpp -o test6
	
test7: test7.cpp Graph.h
	  $(CC) $(CFLAGS) test7.cpp -o test7
	
test8: test8.cpp Graph.h
	  $(CC) $(CFLAGS) test8.cpp -o test8
	
test9: test9.cpp Graph.h
	  $(CC) $(CFLAGS) test9.cpp -o test9
	
test10: test10.cpp Graph.h
	  $(CC) $(CFLAGS) test10.cpp -o test10
	
test11: test11.cpp Graph.h
	  $(CC) $(CFLAGS) test11.cpp -o test11
	
test12: test12.cpp Graph.h
	  $(CC) $(CFLAGS) test12.cpp -o test12

test13: test13.cpp Graph.h
	  $(CC) $(CFLAGS) test13.cpp -o test13

test14: test14.cpp Graph.h
	  $(CC) $(CFLAGS) test14.cpp -o test14

test15: test15.cpp Graph.h
	  $(CC) $(CFLAGS) test15.cpp -o test15

clean:
	rm test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15
